<?php
define("HOST1","localhost");
define("USER1","grupo23");
define("PORT1","5432");
define("PASSWORD1","grupo23");
define("DATABASE1","grupo23E3");
define("MONGO_DATABASE1",'grupo23');

define("HOST2","localhost");
define("USER2","grupo46");
define("PORT2","5432");
define("PASSWORD2","grupo46");
define("DATABASE2","grupo46E3");
define("MONGO_DATABASE2",'grupo46');
/*
define("cursos",'cursos');
define("universidades",'universidades');
define("alumnos",'alumnos');
*/
 ?>
